---
abstract: 'command-line for manipulating your todoist.com todo list'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-todoist
requires:
  AppConfig::Std: '0'
  Carp: '0'
  File::Slurp: '0'
  Net::Todoist: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/neilbowers/App-todoist
  repository: https://github.com/neilbowers/App-todoist.git
version: '0.02'
